modLoader="kotlinforforge"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="appliedcreate"
logoFile="appliedcreate_icon.png"
version="${file.jarVersion}"
displayName="Applied Create"
authors="loliball"
description='''A bridge between Create and Applied Energistics 2 — stress storage, P2P tunnels, pattern providers, and more.'''

[[dependencies.appliedcreate]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.appliedcreate]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.appliedcreate]]
    modId="create"
    mandatory=true
    versionRange="[6.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.appliedcreate]]
    modId="kotlinforforge"
    mandatory=true
    versionRange="[4.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.appliedcreate]]
    modId="ae2"
    mandatory=true
    versionRange="[15.0,)"
    ordering="AFTER"
    side="BOTH"

[[mixins]]
config="appliedcreate.mixins.json"
